config/routes.rb
Rails.application.routes.draw do
  
  get 'movie/index'

  get 'movie/new'

  get 'movie/create'

  root 'movie#index'
  
  get '/tweet', to: 'home#index'

  resources :home
  resources :movie

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def new
  end 

  def create
  	@tweet = SendTweet.new(params[:tweet]).perform
  	render 'index'
  end
end

app/controllers/movie_controller.rb
class MovieController < ApplicationController
  def index
  end

  def new
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<hr>

<%= form_tag home_index_path do  %>


      <%= label_tag :tweet %>
      <%= text_field_tag :tweet %>

      <%= submit_tag "Submit tweet", class: "btn btn-large btn-primary" %>
 <% end %>

<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsService</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movie/create.html.erb
<h1>Movie#create</h1>
<p>Find me in app/views/movie/create.html.erb</p>

app/views/movie/index.html.erb
<h1>Movie#index</h1>
<p>Find me in app/views/movie/index.html.erb</p>


<%= form_tag home_index_path do  %>


      <%= label_tag :movie %>
      <%= text_field_tag :movie %>

      <%= submit_tag "Submit tweet", class: "btn btn-large btn-primary" %>
 <% end %>

app/views/movie/new.html.erb
<h1>Movie#new</h1>
<p>Find me in app/views/movie/new.html.erb</p>